// Objective-C API for talking to codexrelay.local/tailcatmobile Go package.
//   gobind -lang=objc -prefix="CR" codexrelay.local/tailcatmobile
//
// File is generated by gobind. Do not edit.

#ifndef __CRTailcatmobile_H__
#define __CRTailcatmobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Path probes the active Tailcat route without exposing endpoint or DERP details.
 */
FOUNDATION_EXPORT NSString* _Nonnull CRTailcatmobilePath(long timeoutMillis);

/**
 * Start creates or reuses the process-local loopback proxy for one Tailcat server.
 */
FOUNDATION_EXPORT NSString* _Nonnull CRTailcatmobileStart(NSString* _Nullable token, long targetPort, NSString* _Nullable cachePath, NSError* _Nullable* _Nullable error);

/**
 * Stop closes the loopback listener, active proxy connections, and Tailcat client.
 */
FOUNDATION_EXPORT void CRTailcatmobileStop(void);

#endif
