
// Objective-C API for talking to the following Go packages
//
//	codexrelay.local/tailcatmobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TailcatMobile_FRAMEWORK_H__
#define __TailcatMobile_FRAMEWORK_H__

#include "CRTailcatmobile.objc.h"
#include "Universe.objc.h"

#endif
